config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: "tasks#index"
  get 'tasks/new', to: 'tasks#new', as: :new
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create', as: :createdtask
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update', as: :update
  delete 'tasks/:id', to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all #calling .all with active Record on Task
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @newtask = Task.new
  end

  def create
    @createdtask = Task.new(task_params)
    @createdtask.save
    redirect_to task_path(@createdtask)
  end

  def edit
    @edittask = Task.find(params[:id])
  end

  def update
    @updatedtask = Task.find(params[:id])
    @updatedtask.update(task_params)
    redirect_to task_path(@updatedtask)
  end

  def destroy
    @destask = Task.find(params[:id])
    @destask.destroy
    redirect_to task_path(@destask)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>You want to edit something:</h1>

<%= form_for(@edittask) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> All the tasks we have: </h1>
  <% @tasks.each do |task| %>
    <% if task["completed"] %>
      <p><input type="checkbox" checked>
    <% else %>
      <p><input type="checkbox">
    <% end %>
    <%= link_to task.title, task_path(task) %></p>
    <%= link_to "Delete me", new_path,  method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>

<%= link_to "Add a new task", new_path %>

app/views/tasks/new.html.erb
<h1>oh no! You have a new task? Tell me.. </h1>

<%= form_for(@newtask) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>


<%=link_to 'Back to all tasks', tasks_path%>

app/views/tasks/show.html.erb
<h1> <%= @task.title%></h1>
<p> <%= @task.details%></p>


<%=link_to 'Edit this task', edit_path%>

<%=link_to 'Back to all tasks', tasks_path%>